### ISSUE TITLE
segmenter  の中に文字列処理のバグがありそう

### ISSUE THREAD

**Issue by tokuhirom** [akaza-im/akaza#183]
```
thread 'main' panicked at 'byte index 30 is out of bounds of `どき ゅめんとの`', libakaza/src/graph/segmenter.rs:90:34
stack backtrace:
   0: rust_begin_unwind
             at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/core/src/panicking.rs:65:14
   2: core::str::slice_error_fail_rt
   3: core::str::slice_error_fail
             at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/core/src/str/mod.rs:86:9
   4: libakaza::graph::segmenter::Segmenter::build
   5: <libakaza::engine::bigram_word_viterbi_engine::BigramWordViterbiEngine<U,B> as libakaza::engine::base::HenkanEngine>::convert
   6: ibus_akaza::context::AkazaContext::_update_candidates
   7: core::ops::function::FnOnce::call_once
   8: ibus_akaza::context::AkazaContext::process_key_event
   9: <unknown>
  10: g_closure_invoke
  11: <unknown>
  12: g_signal_emit_valist
  13: g_signal_emit
  14: <unknown>
  15: <unknown>
  16: g_main_context_dispatch
  17: <unknown>
  18: g_main_loop_run
  19: ibus_main
  20: ibus_akaza::main
```

**Comment by tokuhirom** [comment]
force_range の範囲指定が間違ってる感じが強い。
force_range と、preedit と node_selected とかそのへんが連動しないといけないが更新がうまく連動していないっぽい。
オブジェクトの中に隠蔽した方が良いと思う。

**Comment by tokuhirom** [comment]
#84 とも同根だと思う。

**Comment by tokuhirom** [comment]
入力されたテキストまわりをまとめてオブジェクトとして管理したほうが良いと思う。

**Comment by tokuhirom** [comment]
AkazaContext がそもそもでかすぎるので分割した方が良い。

**Comment by tokuhirom** [comment]
#187 で分割処理をして、状態の管理がだいぶクリアになった。しっかり全部の状態をまとめて更新するようになった。
これでしばらく再現しなければ問題解決。

**Comment by tokuhirom** [comment]
再現しなくなったのでいったんクローズする
