### ISSUE TITLE
out of bounds access

### ISSUE THREAD

**Issue by tokuhirom** [akaza-im/akaza#84]
```
thread 'main' panicked at 'Out of bounds access', ibus-akaza/src/context.rs:495:24
stack backtrace:
   0: rust_begin_unwind
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/panicking.rs:65:14
   2: core::panicking::panic_display
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/panicking.rs:139:5
   3: core::panicking::panic_str
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/panicking.rs:123:5
   4: core::option::expect_failed
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/option.rs:1879:5
   5: core::option::Option<T>::expect
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/option.rs:741:21
   6: <alloc::collections::vec_deque::VecDeque<T,A> as core::ops::index::Index<usize>>::index
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/alloc/src/collections/vec_deque/mod.rs:2939:9
   7: ibus_akaza::context::AkazaContext::build_string
             at ./dev/akaza/ibus-akaza/src/context.rs:495:24
   8: ibus_akaza::context::AkazaContext::refresh
             at ./dev/akaza/ibus-akaza/src/context.rs:568:24
   9: ibus_akaza::context::AkazaContext::_update_candidates
             at ./dev/akaza/ibus-akaza/src/context.rs:524:9
  10: ibus_akaza::context::AkazaContext::extend_clause_right
             at ./dev/akaza/ibus-akaza/src/context.rs:720:9
  11: ibus_akaza::commands::ibus_akaza_commands_map::{{closure}}
             at ./dev/akaza/ibus-akaza/src/commands.rs:52:9
  12: core::ops::function::FnOnce::call_once
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/ops/function.rs:251:5
  13: ibus_akaza::context::AkazaContext::run_callback_by_name
             at ./dev/akaza/ibus-akaza/src/context.rs:407:13
  14: ibus_akaza::context::AkazaContext::process_key_event
             at ./dev/akaza/ibus-akaza/src/context.rs:253:20
  15: ibus_akaza::process_key_event
             at ./dev/akaza/ibus-akaza/src/main.rs:34:5
  16: ibus_akaza_engine_process_key_event
             at ./dev/akaza/ibus-akaza/wrapper.c:64:10
  17: <unknown>
  18: g_closure_invoke
  19: <unknown>
  20: g_signal_emit_valist
  21: g_signal_emit
  22: <unknown>
  23: <unknown>
  24: g_main_context_dispatch
  25: <unknown>
  26: g_main_loop_run
  27: ibus_main
  28: ibus_akaza::main
             at ./dev/akaza/ibus-akaza/src/main.rs:127:9
  29: core::ops::function::FnOnce::call_once
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/ops/function.rs:251:5
```

**Comment by tokuhirom** [comment]
本質解決したら、再現しなくなったのでいったんクローズ
